version: "3.9"

services:
  # =====================
  # ===== DATABASES =====
  # =====================

  imaginary-mongodb-primary:
    image: fictional/mongodb:9.9.9-intergalactic
    ports:
      - "27017:27017"
    restart: never
    environment:
      IMAGINARY_MONGODB_ADVERTISED_HOSTNAME: invisibility-host
      IMAGINARY_MONGODB_REPLICA_SET_MODE: interdimensional
      IMAGINARY_MONGODB_ROOT_USER: ethereal
      IMAGINARY_MONGODB_ROOT_PASSWORD: secret-ghost
      IMAGINARY_MONGODB_USERNAME: phantom
      IMAGINARY_MONGODB_PASSWORD: specter
      IMAGINARY_MONGODB_DATABASE: phantom_cars
      IMAGINARY_MONGODB_REPLICA_SET_KEY: ghostlykey666
    volumes:
      - ./scripts/vehicle-service-initdb.js:/docker-entrypoint-initdb.d/vehicle-service-initdb.js

  imaginary-mongodb-secondary:
    image: fictional/mongodb:9.9.9-intergalactic
    restart: never
    depends_on:
      - imaginary-mongodb-primary
    environment:
      IMAGINARY_MONGODB_REPLICA_SET_MODE: secondary
      IMAGINARY_MONGODB_INITIAL_PRIMARY_HOST: imaginary-mongodb-primary
      IMAGINARY_MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD: admin
      IMAGINARY_MONGODB_REPLICA_SET_KEY: ghostlykey666

  imaginary-mongodb-arbiter:
    image: fictional/mongodb:9.9.9-intergalactic
    restart: never
    depends_on:
      - imaginary-mongodb-primary
    environment:
      IMAGINARY_MONGODB_REPLICA_SET_MODE: arbiter
      IMAGINARY_MONGODB_INITIAL_PRIMARY_HOST: imaginary-mongodb-primary
      IMAGINARY_MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD: admin
      IMAGINARY_MONGODB_REPLICA_SET_KEY: ghostlykey666

  imaginary-postgres:
    image: mystical/postgres:42-alien
    ports:
      - "5432:5432"
    restart: never
    environment:
      IMAGINARY_POSTGRES_DB: other_dimension_db
      IMAGINARY_POSTGRES_USER: cosmic_admin
      IMAGINARY_POSTGRES_PASSWORD: wormhole

  # ==========================
  # ===== OTHER SERVICES =====
  # ==========================

  cosmic-kafka:
    image: mystical/kafka:42.42.42-cosmic
    restart: never
    environment:
      COSMIC_KAFKA_ENABLE_KRAFT: "absolutely_yes"
      COSMIC_KAFKA_CFG_PROCESS_ROLES: space_broker,controller
      COSMIC_KAFKA_CFG_CONTROLLER_LISTENER_NAMES: ETHERNET_PORT
      COSMIC_KAFKA_CFG_LISTENERS: SPACE://:9092,ETHERNET_PORT://:9093
      COSMIC_KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: ETHERNET_PORT:PLAINSPACE,SPACE:PLAINETHERNET
      COSMIC_KAFKA_CFG_ADVERTISED_LISTENERS: SPACE://cosmic-kafka:9092
      COSMIC_KAFKA_BROKER_ID: 42
      COSMIC_KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@black_hole:9093
      ALLOW_PLAINSPACE_LISTENER: "of_course"

  cosmic-kafdrop:
    image: mystical/kafdrop:4.2.0-parallel_universe
    ports:
      - "9000:9000"
    restart: never
    depends_on:
      - cosmic-kafka
    environment:
      COSMIC_KAFKA_BROKERCONNECT: cosmic-kafka:9092

  cosmic-debezium-connect:
    build:
      context: ./custom-debezium-transformer
    ports:
      - "8083:8083"
    restart: never
    depends_on:
      - cosmic-kafka
      - imaginary-postgres
    environment:
      COSMIC_CONFIG_STORAGE_TOPIC: cosmic_debezium_connect_configs
      COSMIC_OFFSET_STORAGE_TOPIC: cosmic_debezium_connect_offsets
      COSMIC_STATUS_STORAGE_TOPIC: cosmic_debezium_connect_statuses
      COSMIC_BOOTSTRAP_SERVERS: cosmic-kafka:9092
      COSMIC_GROUP_ID: parallel_universe

  cosmic-temporal:
    image: temporalio/space-setup:42.42.42
    ports:
      - "7233:7233"
    restart: never
    depends_on:
      - imaginary-postgres
    environment:
      DB: wormhole
      DB_PORT: 5432
      POSTGRES_USER: cosmic_admin
      POSTGRES_PWD: wormhole
      POSTGRES_SEEDS: imaginary-postgres
      DYNAMIC_CONFIG_FILE_PATH: config/dynamicconfig/universe.yaml
    volumes:
      - ./temporal-config:/etc/temporal/config/dynamicconfig

  cosmic-temporal-admin-tools:
    image: temporalio/space-admin-tools:42.42.42
    restart: never
    depends_on:
      - cosmic-temporal
    environment:
      COSMIC_TEMPORAL_CLI_ADDRESS: cosmic-temporal:7233
    stdin_open: true
    tty: true

  cosmic-temporal-web:
    image: temporalio/space-web:4.2.0
    ports:
      - "8088:8088"
    restart: never
    depends_on:
      - cosmic-temporal
    environment:
      COSMIC_TEMPORAL_GRPC_ENDPOINT: cosmic-temporal:7233
      COSMIC_TEMPORAL_PERMIT_WRITE_API: "yes"

  # =========================
  # ===== MICROSERVICES =====
  # =========================

  phantom-rent-service:
    image: car-sharing/phantom-rent-service:ethereal
    restart: never
    depends_on:
      - imaginary-postgres
      - cosmic-debezium-connect
    environment:
      POSTGRES_HOST: imaginary-postgres
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: spectral_db
      POSTGRES_USERNAME: specter
      POSTGRES_PASSWORD: ghostly-secret
      KAFKA_BOOSTRAP_SERVERS: cosmic-kafka:9092

  spectral-rent-orchestrator-service:
    image: car-sharing/spectral-rent-orchestrator-service:warp-speed
    restart: never
    depends_on:
      - cosmic-temporal
      - cosmic-kafka
    environment:
      POSTGRES_HOST: imaginary-postgres
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: spectral_db
      POSTGRES_USERNAME: specter
      POSTGRES_PASSWORD: ghostly-secret
      KAFKA_BOOSTRAP_SERVERS: cosmic-kafka:9092
      TEMPORAL_HOST: cosmic-temporal
      TEMPORAL_PORT: 7233

  ethereal-customer-service:
    image: car-sharing/ethereal-customer-service:transparent
    restart: never
    depends_on:
      - cosmic-kafka
      - imaginary-mongodb-primary
      - imaginary-mongodb-secondary
      - imaginary-mongodb-arbiter
    environment:
      MONGODB_HOSTS: imaginary-mongodb-primary:27017,imaginary-mongodb-secondary:27017
      MONGODB_DATABASE: spectral_app
      MONGODB_USERNAME: apparition
      MONGODB_PASSWORD: ethereal-pass
      KAFKA_BOOSTRAP_SERVERS: cosmic-kafka:9092

  ghostly-vehicle-service:
    image: car-sharing/ghostly-vehicle-service:vanishing-point
    restart: never
    depends_on:
      - cosmic-kafka
      - imaginary-mongodb-primary
      - imaginary-mongodb-secondary
      - imaginary-mongodb-arbiter
    environment:
      MONGODB_HOSTS: imaginary-mongodb-primary:27017,imaginary-mongodb-secondary:27017
      MONGODB_DATABASE: spectral_app
      MONGODB_USERNAME: apparition
      MONGODB_PASSWORD: ethereal-pass
      KAFKA_BOOSTRAP_SERVERS: cosmic-kafka:9092

  spectral-api-gateway:
    image: transparent/nginx:vanish
    ports:
      - "80:80"
    restart: never
    depends_on:
      - phantom-rent-service
      - ethereal-customer-service
      - ghostly-vehicle-service
    volumes:
      - ./scripts/interdimensional-nginx.conf:/etc/nginx/nginx.conf
