version: "3.9"
services:
  # =====================
  # ===== DATABASES =====
  # =====================

  mongodb-primary:
    image: bitnami/mongodb:4.4.8-debian-10-r48
    ports:
      - "27017:27017"
    restart: unless-stopped
    environment:
      MONGODB_ADVERTISED_HOSTNAME: mongodb-primary
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_ROOT_USER: root
      MONGODB_ROOT_PASSWORD: admin
      MONGODB_USERNAME: user
      MONGODB_PASSWORD: password
      MONGODB_DATABASE: app
      MONGODB_REPLICA_SET_KEY: replicasetkey123
    volumes:
      - ./scripts/vehicle-service-initdb.js:/docker-entrypoint-initdb.d/vehicle-service-initdb.js

  mongodb-secondary:
    image: bitnami/mongodb:4.4.8-debian-10-r48
    restart: unless-stopped
    depends_on:
      - mongodb-primary
    environment:
      MONGODB_REPLICA_SET_MODE: secondary
      MONGODB_INITIAL_PRIMARY_HOST: mongodb-primary
      MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD: admin
      MONGODB_REPLICA_SET_KEY: replicasetkey123

  mongodb-arbiter:
    image: bitnami/mongodb:4.4.8-debian-10-r48
    restart: unless-stopped
    depends_on:
      - mongodb-primary
    environment:
      MONGODB_REPLICA_SET_MODE: arbiter
      MONGODB_INITIAL_PRIMARY_HOST: mongodb-primary
      MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD: admin
      MONGODB_REPLICA_SET_KEY: replicasetkey123

  postgres:
    image: debezium/postgres:13-alpine
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  # ==========================
  # ===== OTHER SERVICES =====
  # ==========================

  kafka:
    image: bitnami/kafka:3.3.1-debian-11-r29
    restart: unless-stopped
    environment:
      KAFKA_ENABLE_KRAFT: "yes"
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      ALLOW_PLAINTEXT_LISTENER: "yes"

  kafdrop:
    image: obsidiandynamics/kafdrop:3.27.0
    ports:
      - "9000:9000"
    restart: unless-stopped
    depends_on:
      - kafka
    environment:
      KAFKA_BROKERCONNECT: kafka:9092

  debezium-connect:
    build:
      context: ./custom-debezium-transformer
    ports:
      - "8083:8083"
    restart: unless-stopped
    depends_on:
      - kafka
      - postgres
    environment:
      CONFIG_STORAGE_TOPIC: debezium_connect_configs
      OFFSET_STORAGE_TOPIC: debezium_connect_offsets
      STATUS_STORAGE_TOPIC: debezium_connect_statuses
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1

  temporal:
    image: temporalio/auto-setup:1.14.4
    ports:
      - "7233:7233"
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      DB: postgresql
      DB_PORT: 5432
      POSTGRES_USER: admin
      POSTGRES_PWD: admin
      POSTGRES_SEEDS: postgres
      DYNAMIC_CONFIG_FILE_PATH: config/dynamicconfig/development.yaml
    volumes:
      - ./temporal-config:/etc/temporal/config/dynamicconfig

  temporal-admin-tools:
    image: temporalio/admin-tools:1.14.2
    restart: unless-stopped
    depends_on:
      - temporal
    environment:
      TEMPORAL_CLI_ADDRESS: temporal:7233
    stdin_open: true
    tty: true

  temporal-web:
    image: temporalio/web:1.13.0
    ports:
      - "8088:8088"
    restart: unless-stopped
    depends_on:
      - temporal
    environment:
      TEMPORAL_GRPC_ENDPOINT: temporal:7233
      TEMPORAL_PERMIT_WRITE_API: "true"

  # =========================
  # ===== MICROSERVICES =====
  # =========================

  rent-service:
    image: car-sharing/rent-service
    restart: unless-stopped
    depends_on:
      - postgres
      - debezium-connect
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: db
      POSTGRES_SCHEMA: rent-service
      POSTGRES_USERNAME: admin
      POSTGRES_PASSWORD: admin
      KAFKA_BOOSTRAP_SERVERS: kafka:9092

  rent-orchestrator-service:
    image: car-sharing/rent-orchestrator-service
    restart: unless-stopped
    depends_on:
      - temporal
      - kafka
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: db
      POSTGRES_USERNAME: admin
      POSTGRES_PASSWORD: admin
      KAFKA_BOOSTRAP_SERVERS: kafka:9092
      TEMPORAL_HOST: temporal
      TEMPORAL_PORT: 7233

  customer-service:
    image: car-sharing/customer-service
    restart: unless-stopped
    depends_on:
      - kafka
      - mongodb-primary
      - mongodb-secondary
      - mongodb-arbiter
    environment:
      MONGODB_HOSTS: mongodb-primary:27017,mongodb-secondary:27017
      MONGODB_DATABASE: app
      MONGODB_USERNAME: user
      MONGODB_PASSWORD: password
      KAFKA_BOOSTRAP_SERVERS: kafka:9092

  vehicle-service:
    image: car-sharing/vehicle-service
    restart: unless-stopped
    depends_on:
      - kafka
      - mongodb-primary
      - mongodb-secondary
      - mongodb-arbiter
    environment:
      MONGODB_HOSTS: mongodb-primary:27017,mongodb-secondary:27017
      MONGODB_DATABASE: app
      MONGODB_USERNAME: user
      MONGODB_PASSWORD: password
      KAFKA_BOOSTRAP_SERVERS: kafka:9092

  payment-service:
    image: car-sharing/payment-service
    restart: unless-stopped
    depends_on:
      - kafka
      - postgres
      - debezium-connect
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: db
      POSTGRES_USERNAME: admin
      POSTGRES_PASSWORD: admin
      KAFKA_BOOSTRAP_SERVERS: kafka:9092
      STRIPE_API_KEY: ${STRIPE_API_KEY}

  api-gateway:
    image: nginx:latest
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - rent-service
      - customer-service
      - vehicle-service
    volumes:
      - ./scripts/nginx-gateway.conf:/etc/nginx/nginx.conf

  structurizr:
    image: structurizr/lite:3193
    restart: unless-stopped
    ports:
      - "8080:8080"
